
-- Run in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  phone text,
  plan text not null default 'free',
  credits_seconds integer not null default 0,
  account_status text not null default 'active',
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
create policy "user reads own profile" on public.profiles for select using (auth.uid() = id);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text,
  provider_reference text unique,
  plan text not null,
  status text not null default 'pending',
  current_period_end timestamptz,
  created_at timestamptz not null default now()
);
alter table public.subscriptions enable row level security;
create policy "user reads own subscription" on public.subscriptions for select using (auth.uid() = user_id);

create table if not exists public.usage_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  seconds integer not null default 0,
  provider_cost_usd numeric(12,4),
  status text not null,
  created_at timestamptz not null default now()
);
alter table public.usage_ledger enable row level security;
create policy "user reads own usage" on public.usage_ledger for select using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,display_name,phone)
  values(new.id,new.raw_user_meta_data->>'name',new.raw_user_meta_data->>'phone')
  on conflict(id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();


create table if not exists public.tool_entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tool_id text not null,
  plan text not null default 'free',
  status text not null default 'active',
  credits_seconds integer not null default 0,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id, tool_id)
);
alter table public.tool_entitlements enable row level security;
create policy "user reads own tool entitlements" on public.tool_entitlements
for select using (auth.uid() = user_id);

-- Default entitlement for the first tool. Change/remove before commercial launch if desired.
create or replace function public.ensure_default_tool_entitlement()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.tool_entitlements(user_id,tool_id,plan,status,credits_seconds)
  values(new.id,'cinematic-movie-factory','free','active',0)
  on conflict(user_id,tool_id) do nothing;
  return new;
end; $$;

drop trigger if exists on_profile_tool_entitlement on public.profiles;
create trigger on_profile_tool_entitlement after insert on public.profiles
for each row execute procedure public.ensure_default_tool_entitlement();


alter table public.profiles add column if not exists role text not null default 'user';

create table if not exists public.tool_catalog (
  tool_id text primary key,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.tool_catalog(tool_id,name,description)
values ('cinematic-movie-factory','Cinematic Movie Factory','Automated realistic/local/whiteboard movie creation')
on conflict (tool_id) do update set name=excluded.name,description=excluded.description;

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  provider text not null,
  provider_reference text unique,
  tool_id text,
  plan text,
  amount numeric(12,2),
  currency text,
  status text not null,
  raw_event jsonb,
  created_at timestamptz not null default now()
);
alter table public.payment_events enable row level security;
create policy "user reads own payment events" on public.payment_events for select using (auth.uid() = user_id);

create table if not exists public.tool_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tool_id text not null,
  action text not null,
  seconds integer not null default 0,
  mode text,
  status text not null default 'ok',
  created_at timestamptz not null default now()
);
alter table public.tool_usage enable row level security;
create policy "user reads own tool usage" on public.tool_usage for select using (auth.uid() = user_id);
